<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {

    $checklist = [
        'Pre Flight' => [
            'EFB: Import Flight Plan',
            'Overhead: Battery 1 / 2 ON',
            'Overhead: External Power ON',
            'Overhead: Crew Supply ON',
            'Overhead: Ground Control ON',
            'Overhead: Press and hold CVR to test',
            'Overhead: Fire Tests',
            'Overhead: NAV ADRs x 3 to NAV',
            'Overhead: No Smoking AUTO',
            'Overhead: Emergency Signs Armed',
            'EFB: Set QNH on Standby',
            'Select VHF1 and Tune',
            'Pedestal: Weather Radar OFF',
            'Throttles: Spoilers Disarmed',
            'Switching Panel NORM x 4',
            'THRUST IDLE',
            'Engine Starters OFF',
            'Engine Mode Selector MIDDLE',
            'Parking Brake ON',
            'Flaps NONE',
            'Squeaking 2000 and set to standby',
            'Set the QNH on the FMC (Check both sides)',
            'FDx2 ON',
            'CSTRx2 ON',
            'Set the Altitude to first cleared altitude',
            'APU Master ON',
            'WAIT 3 Seconds',
            'APU Start',
            'Wait ONE minute',
            'Set screen brightness for all screens',
            'APU Bleed ON',
            'Load Aircraft from EFB',
        ],
        'MCDU' => [
            'Check Nav Data',
            'Init Request',
            'Flight number',
            'Cost Index',
            'Cruise / temp',
            'Wind request',
            'Setup SID / STAR',
            'Copy the active FP',
            'Check radio frequencies on charts',
            'Tune them if needed',
            'Switch VOR1/2 if you want to see them',
            'EFB Mass and Balance ZFW / MACZFW go into ZFW / ZFWCG',
            'Block is on the EFB under “Fuel Planned” - Check this is what we have onboard, and enter this into the MCDU 5300 would be 5.3 in the MCDU',
            'Check alternate fuel from the OFP and update if needed',
            'EFB use the departure perf app to calculate the values',
            'Flaps 1 / No THS needed',
            'Flex to temp (higher number means lower thrust)',
            'V1 / VR / V2',
            'ATSU messages / Accept the Loadsheet.',
        ],
        'Pushback' => [
            'Turn on Fuel Pumps X 6',
            'External Power OFF',
            'Seatbelts ON',
            'EFB: Remove Ground Services and Chocks',
            'Beacon Light ON',
            'Transponder AUTO',
            'Parking Brake OFF',
            'Start Pushback',
            'Engine Mode Selector IGNITION',
            'Start Engine 2',
            'Once we see AVAIL move on',
            'Start Engine 1',
            'Once we see AVAIL move on',
            'Parking Brake ON',
            'Engine Mode Selector NORMAL',
            'APU Bleed OFF',
            'Anti Ice if needed',
            'APU Master OFF',
            'Spoilers ARMED',
            'Set Flaps',
            'Get trim setting from final load sheet MACTOW',
            'Set the TRIM WHEEL',
            'Weather Radar ON',
            'Transponder SET',
            'Auto brake MAX',
            'TO Config screen enabled in centre',
            'Taxi ON',
            'Parking Brake OFF',
        ],
        'Lights' => [
            'Nav Lights ON',
            'Logo Lights ON',
        ],
        'Before Takeoff' => [
            'Wing Lights ON if night',
            'Strobe Lights ON',
            'Runway TO Lights ON',
            'Landing Lights ON',
            'TCAS TARA',
            'Parking Brake OFF',
            'Position ON runway',
        ],
        'Take Off' => [
            'Set Flex',
            'Rotate',
            'Gear up',
            'Set CLIMB',
            'AP ON',
            'Flaps 0',
            'Spoilers Disarmed',
            'At flight level 6k or whatever, switch to STD pressure on BOTH sides',
            'Standby instrument also to STD',
            '10k Seatbelts OFF',
        ],
        'Cruise' => [
            'Top of descent is a little blue line',
            'If we cant get to the expected cruise altitude then we need to goto PROG and update the cruise altitude to what we can get to, this will put us in ALT CRZ on the PFD',
            'TCAS Below',
        ],
        'Descent' => [
            'Enter some constraint speeds on the way in on the approach to help slow things down, the speeds shown are what we will be at, a magenta dot next to it signifies we will be adhering to that constraint, if it has a yellow circle around it, then its predicting it wont make that speed / alt.',
            'Set autobrake if we calculate a new stopping distance on the EFB',
            'TOD marker is a white line',
            'After TOD!! Set ALT to whatever the TRANSITION is, example 6k',
            'On The PERF page -> Next Phase to “APPR” -> set the QNH / Temperature / Wind of the destination airport (found in EFB)',
            'Seatbelts ON',
            'Under 10k Landing Lights ON',
            'Set local pressure of airport on standby instrument',
            'Set altitude and managed descent',
            'Come off STD and set QNH of airport',
            '230 knots max speed for flaps 1',
            '180 knots is a great approach speed',
        ],
        'Landing' => [
            'Click LOC to get onto the localiser, on airbus we need this before we can get in the glide slope, so make sure to enable this!',
            'Flaps 2 on the glide slope!',
            'Once you see LOC* on the main panel, we can enable APR mode',
            'Also make sure both APs are enabled',
            'Managed mode for speed ON',
            'Landing gear',
            'Spoilers ARM',
            'Lights ON',
            '30ft thrust to idle',
        ],
        'Post Flight' => [
            'TBD',
        ],
        'Power Down' => [
            'TBD',
        ],
    ];

    return view('checklist', [
        'checklist' => $checklist,
    ]);
});
