<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {

    $checklist = [
        'Preparation' => [
            'Pedestal: Parking Brake ON',
            'EFB: Import Flight Plan',
            'EFB: Load Aircraft PAX / Cargo',
            'Overhead: Battery 1 ON',
            'Overhead: Battery 2 ON',
            'Overhead: External Power ON',
            'Overhead: Crew Supply Oxygen ON',
            'Overhead: Ground Control ON (FDR on Ground)',
            'Overhead: ADR 1/2/3 to NAV',
            'Overhead: Strobe Lights AUTO',
            'Overhead: Nav & Logo ON (1 or 2)',
            'Overhead: Beacon OFF',
            'Overhead: Runway Turnoff OFF',
            'Overhead: Landing Lights OFF',
            'Overhead: Taxi Lights OFF',
            'Overhead: No Smoking AUTO',
            'Overhead: Emergency Exit Lights ARMED',
            'Overhead: Seatbelts ON (when fully fuelled)',
            'Overhead: Fuel Pumps x 6 ON',
            'Instrument Panel: Set QNH on Standby Altimeter',
            'Instrument Panel: Antiskid / Nose Wheel Steering ON',
            'Instrument Panel: Reset Clock',
            'Radio: Transponder STANDBY',
            'Radio: TCAS STANDBY',
            'Radio: IDENT ABV',
            'MCDU: ATSU -> AOC MENU -> WX REQUEST -> SET ICAO -> METAR (Y) -> SEND',
            'MCDU: ATSU -> AOC MENU -> RCVD MSG -> WEATHER DATA',
            'MCDU: ATSU -> AOC MENU -> FLIGHT INIT -> INIT DATA REQUEST',
            'MCDU: ---=== (D)ata (I)nit A (F)light Plan (S)econdary Flight Plan (R)adios (I)nit B (P)erformance ===---',
            'MCDU: DATA -> Aircraft Status Check',
            'MCDU: INIT A -> INIT REQUEST',
            'MCDU: INIT A -> Enter Flight # / CI / CRZ FL',
            'MCDU: INIT A -> Check Ground Temperature',
            'MCDU: INIT A -> Wind -> Wind Request',
            'MCDU: F-PLN -> Click Airport -> Departure -> Runway -> SID -> INSERT',
            'MCDU: AIRPORT -> Click Airport -> Arrival -> Runway -> STAR -> INSERT',
            'MCDU: F-PLN -> Check Route for Discontinuities',
            'MCDU: SEC F-PLN -> Copy Active',
            'MCDU: RAD NAV -> Check Radio Frequencies',
            'MCDU: INIT B -> Fill from EFB Mass & Balance',
            'EFB: Performance Calculator -> Sync Loadsheet -> Sync Live WX -> Calculate',
            'MCDU: PERF -> Fill Flaps / Flex Temp (More Flex = Less Thrust)',
            'MCDU: PERF -> Fill V1 / VR / V2',
            'MCDU: Check Clean Speed Matches',
            'MCDU 2: MCDU Menu -> ATSU -> AOC Menu -> RCVD MSGS -> LOADSHEET -> ACCEPT',
            'EFIS: PF / FO Select CSTR',
            'EFIS: PF / FO Set QNH',
            'MCP: Set Cleared Altitude',
            'MCP: Flight Directors ON (1 FD 2)',
            'PFD: Check Blue CLB / NAV / 1 FD 2',
            'Overhead: APU Master ON (wait 3s)',
            'Overhead: APU Start (wait until avail)',
            'Overhead: External Power OFF',
            'EFB: Ground Services -> Connect Tug',
            'EFB: Ground Services -> Disconnect GPU',
            'Overhead: APU Bleed ON',
            'EFB: Pilot Brief -> Documents -> Normal Checklist -> Before Start Checklist',
            'RADIO: Squawk 2000',
            'RADIO: Transponder AUTO',
            'Lights: Beacon ON',
            'Pedestal: Parking Brake OFF',
            'Pushback',
            'Pedestal: Set Parking Brake AFTER Pushback',
            'EFB: Ground Services -> Disconnect TUG',
            'Pedestal: Engine Mode Selector IGNITION START',
            'Pedestal: Engine 2 Start',
            'Engine Display: Avail Once Engine 2 Running',
            'Pedestal: Engine 1 Start',
            'Engine Display: Avail Once Engine 1 Running',
            'Pedestal: Engine Mode Selector NORMAL',
            'Overhead: APU Bleed OFF',
            'Overhead: APU Master OFF',
            'Pedestal: Spoilers ARMED',
            'Pedestal: Flaps 1',
            'Pedestal: Set Trim to MACTOW % from EFB PERF',
            'EFB: Pilot Brief -> Documents -> Normal Checklist -> After Start Checklist',
        ],
        'Start Taxi' => [
            'MCP: Press Chrono',
            'Overhead: Nose Light to TAXI',
            'Overhead: Runway Turnoff ON',
            'Pedestal: Parking Brake OFF',
            'Pedestal: WX Radar ON',
            'Pedestal: Predictive Windshear AUTO',
            'Radio: TCAS TA/RA',
            'Instrument Panel: Auto Brake MAX',
            'TO Config: ECAM Memo -> Check ALL Green NO BLUE',
            'EFB: Pilot Brief -> Documents -> Normal Checklist -> Before Takeoff Checklist',
        ],
        'Light Configuration' => [
            'Overhead: Landing Lights ON',
            'Overhead: Strobe Lights ON',
            'Overhead: Nose Light to TO',
        ],
        'Before Take Off' => [
            'Pedestal: Parking Brake OFF',
            'Rudder: Toe Brakes HOLD',
            'Pedestal: 50% N1 Thrust',
            'Rudder: Toe Brakes RELEASE',
            'Pedestal: Thrust Levers to FLX MCT',
            'Rotate',
        ],
        'Climb' => [
            'Instrument Panel: Gear UP',
            'MCP: AP 1 ON',
            'Pedestal: Thrust Levers to CLIMB',
            'Pedestal: Flaps 1 (When Above Green F on Tape)',
            'Pedestal: Flaps 0 (When Above Green S on Tape)',
            'Pedestal: Spoilers Disarmed',
            'Lights: Runway Turnoff OFF',
            'Lights: Nose Gear Light OFF',
        ],
        'After Take Off' => [
            'EFIS: PF / FO STD Pressure (PULL)',
            'Instrument Panel: Press for STD',
            'EFB: Pilot Brief -> Documents -> Normal Checklist -> After Takeoff Checklist',
            'Overhead: Landing Lights OFF @ 10,000ft',
            'Overhead: Seatbelts OFF @ 10,000ft',
        ],
        'Cruise' => [
            'MCP: Push = Managed By FMGS, PULL = DO IT NOW',
            'MCP: Set Altitude (PULL for Open Climb) (PUSH for Managed Climb)',
            'Overhead: Engine Anti-Ice (IF Total Air Temp < 10 Degrees)',
            'ECAM: Check',
            'MCDU: PROG -> Check CRZ ALT',
            'RADIO: TCAS Below',
            'ECAM: Check Status Pages',
        ],
        'Descent Preparation' => [
            'MCDU: ---=== (F)light Plan (R)adios (P)rog (P)erformance (F)uel Prediction (S)econdary Flight Plan ===---',
            'MCDU: F-PLN -> Check / Set STAR',
            'MCDU: RAD NAV -> Check Radio Frequencies',
            'MCDU: PROG -> Check Progress',
            'MCDU: PERF -> Next Phase (DES) -> Next Phase (APPR) -> Enter Destination QNH / Temperature / Wind / Baro',
            'MCDU: FUEL PRED -> Check Fuel Prediction',
            'MCDU: SEC F-PLN -> Copy Active',
            'EFB: Performance Calculator',
            'Instrument Panel: Auto Brake LOW / MEDIUM',
        ],
        'Descent' => [
            'MCP: Set Altitude and PUSH',
            'Overhead: Seatbelts ON @ 10,000ft',
            'Overhead: Landing Lights ON @ 10,000ft',
            'EFIS: PF / FO LS ON (Localiser Only If Precision Approach)',
            'EFIS: PF / FO Set QNH (TWIST PUSH)',
            'Instrument Panel: Set QNH on Standby Altimeter',
            'EFB: Pilot Brief -> Documents -> Normal Checklist -> Approach Checklist',
        ],
        'Hold' => [
            'MCDU: F-PLN -> Select Waypoint -> HOLD -> Computed (or add details)',
        ],
        'Landing' => [
            'Pedestal: Flaps 1',
            'MCP: Press APR just before the ILS',
            'MCP: Check LOC is ON',
            'MCP: Check Both APs are ON',
            'EFB: Pilot Brief -> Documents -> Normal Checklist -> Landing Checklist',
            'Pedestal: Flaps 2',
            'Pedestal: Landing Gear DOWN (6m OUT)',
            'Pedestal: Spoliers ARMED',
            'Pedestal: Flaps 3',
            'Pedestal: Flaps 4',
            'Lights: Nose Light Taxi ON',
            'Lights: Runway Turnoff ON',
            'ECAM: Memo No Blue',
            'Stick: AP OFF',
            'AUDIO: 30ft Start Flare',
            'Pedestal: Thrust Levers to IDLE (Before Touchdown)',
            'AUDIO: RETARD! RETARD! RETARD! (Thrust Levers are NOT IDLE!)',
            'Pedestal: Reverse Thrust',
        ],
        'Post Flight' => [
            'Overhead: Landing Lights OFF',
            'Pedestal: Flaps 0',
            'Pedestal: Speedbrake DOWN',
            'Overhead: Check Lights',
        ],
        'Power Down' => [
            'Pedestal: Parking Brake ON',
            'EFB: Set Chocks',
            'Overhead: Taxi Lights OFF',
            'Overhead: External Power ON',
            'Pedestal: Engine 1 OFF',
            'Pedestal: Engine 2 OFF',
            'Overhead: Battery 1 OFF',
            'Overhead: Battery 2 OFF',
            'Overhead: Seatbelts OFF',
            'Clean Up',
        ],
    ];

    return view('checklist', [
        'checklist' => $checklist,
    ]);
});
